export const properties = [
  'Nome',
  'Peso',
  'Altura',
  'Região (Norte/Sul)',
  'Vagabundo',
  'Jogos principais',
];

export const characters = [
  {
    name: 'Felipe',
    weight: 54,
    height: 1.82,
    region: 'Sul',
    unemployed: true,
    mainGames: ['osu!', 'TFT'],
  },
  {
    name: 'Henrique',
    weight: 69,
    height: 1.69,
    region: 'Sul',
    unemployed: false,
    mainGames: ['Pokémon', 'Valorant'],
  },
  {
    name: 'David',
    weight: 85,
    height: 1.87,
    region: 'Sul',
    unemployed: false,
    mainGames: ['League of Legends'],
  },
  {
    name: 'Giovanni',
    weight: 115,
    height: 1.85,
    region: 'Sul',
    unemployed: true,
    mainGames: ['League of Legends'],
  },
  {
    name: 'Bruno',
    weight: 100,
    height: 1.8,
    region: 'Sul',
    unemployed: true,
    mainGames: ['League of Legends', 'Legends of Runeterra'],
  },
  {
    name: 'Gustavo',
    weight: 110,
    height: 1.83,
    region: 'Sul',
    unemployed: false,
    mainGames: ['GTA RP'],
  },
  {
    name: 'João',
    weight: 85,
    height: 1.82,
    region: 'Sul',
    unemployed: true,
    mainGames: ['League of Legends', 'FIFA'],
  },
  {
    name: 'Neto',
    weight: 72,
    height: 1.72,
    region: 'Norte',
    unemployed: false,
    mainGames: ['League of Legends', 'FIFA'],
  },
  {
    name: 'Thiago',
    weight: 75,
    height: 1.83,
    region: 'Norte',
    unemployed: false,
    mainGames: ['League of Legends'],
  },
  {
    name: 'Paulo',
    weight: 67,
    height: 1.68,
    region: 'Norte',
    unemployed: true,
    mainGames: ['osu!', 'Honkai'],
  },
  {
    name: 'GVC',
    weight: 85,
    height: 1.8,
    region: 'Sul',
    unemployed: true,
    mainGames: ['osu!', 'TFT'],
  },
  {
    name: 'Carlos',
    weight: 85,
    height: 1.65,
    region: 'Sul',
    unemployed: true,
    mainGames: ['League of Legends'],
  },
  {
    name: 'Verona',
    weight: 60,
    height: 1.83,
    region: 'Sul',
    unemployed: false,
    mainGames: ['League of Legends', 'Counter Strike'],
  },
];
